"""create users table

Revision ID: d9b10d8615e1
Revises:
Create Date: 2026-01-08 20:49:37.423733

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "d9b10d8615e1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False, comment="User unique identifier"),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="User email address (unique, lowercase)",
        ),
        sa.Column(
            "password_hash", sa.String(length=60), nullable=False, comment="Bcrypt password hash"
        ),
        sa.Column("full_name", sa.String(length=255), nullable=False, comment="User full name"),
        sa.Column(
            "role",
            sa.Enum("CUSTOMER", "COURIER", "RESTAURANT_OWNER", "ADMIN", name="user_role_enum"),
            nullable=False,
            comment="User role in the system",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Is user active (soft delete)"
        ),
        sa.Column(
            "phone", sa.String(length=20), nullable=True, comment="User phone number (optional)"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Creation timestamp (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last update timestamp (UTC)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
